### ISSUE TITLE
Support feature improvement

### ISSUE THREAD

**Issue by Quannh1511** [DragoNext/AqwDoIhave#1]
Hello DragoNext,

My name is Quan, I have a suggestion about item comparison, when getting data on aqw manage page, please process housing items (floor, wall) please cut its quantity for a more accurate comparison. And here is the list of suffixes of the names, which I give you so that you can handle it in a better way. One more thing, your source code is very hard to read, which makes it quite difficult for me to assist you, but that's okay, I'll have new ideas when testing future versions.

Good luck.

List of suffixes of names
[suffixes of names.txt](https://github.com/DragoNext/AqwDoIhave/files/9930449/suffixes.of.names.txt)

**Comment by DragoNext** [comment]
Hi Quan,

Thank you for mentioning quantity for housing items, forgot about these.
And the suffixes, I will add them later as, I will refactor the code as you say it is not readable in that state, it is mostly because it was made quite quickly didn't have time to make it much readable, but will take time to make it better.

Thanks for you contribution.

**Comment by DragoNext** [comment]
Hi Again Quan hope you well,

I've done refactoring still isn't great to read but a lot better than previously, using these suffixes will be hard as currently there are 2 cases some items https://account.aq.com/AQW/Inventory have already some of them for example house items (L) and (R) if we delete that there will be no distinction from them example: [https://imgur.com/a/IbVpbWg](url)

Just some of them that don't appear on the account site can be used, right now this is temporary fix, suffixes should be mostly used but it's widely inconsistent over aqwwiki that's why i abstain from adding more as it will cause problems with matching, but will add some of them for sure.

There is another problem with classes as on wiki there is usually few versions of them one AC one 0 AC and there is no real method of differentiating them as  account site doesn't provide enough info to match appropriate items.

There are few solutions on my mind currently but each one of them has problems mainly by having not much information from account :|

**Comment by Quannh1511** [comment]
Hello DragoNext,

I understand your problem, suffixes are essential to identify an item, but aqw manage doesn't provide price information, it's only known in buyback, I have no solution about it either. this part. We can ask the aqw manage to add the price to make it easier to compare, but it is very difficult to ask them.

I think you just need to keep the house item suffixes, which I think is possible.

I will still assist you with some issues as much as I can.

Good luck.
